In [1]:
import torch

In [2]:
x = torch.rand((2, 3))

In [3]:
x

tensor([[0.3407, 0.6799, 0.1200],
        [0.1364, 0.4959, 0.8097]])

In [4]:
x.shape

torch.Size([2, 3])

In [5]:
x.type()

'torch.FloatTensor'

In [12]:
x.T.shape

torch.Size([3, 2])

In [13]:
x.T

tensor([[0.3407, 0.1364],
        [0.6799, 0.4959],
        [0.1200, 0.8097]])

In [6]:
x+x

tensor([[0.6814, 1.3599, 0.2401],
        [0.2729, 0.9919, 1.6194]])

In [10]:
torch.matmul(x, x.T)

tensor([[0.5928, 0.4809],
        [0.4809, 0.9202]])

In [11]:
torch.matmul(x.T, x)

tensor([[0.1347, 0.2993, 0.1514],
        [0.2993, 0.7083, 0.4832],
        [0.1514, 0.4832, 0.6700]])

In [18]:
x = torch.arange(6)

In [19]:
x

tensor([0, 1, 2, 3, 4, 5])

In [21]:
x = x.view(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [23]:
x = torch.rand((2, 3))
y = x.view(1, 6)
x, y

(tensor([[0.1764, 0.5388, 0.1691],
         [0.2029, 0.3977, 0.6300]]),
 tensor([[0.1764, 0.5388, 0.1691, 0.2029, 0.3977, 0.6300]]))

In [24]:
x = torch.rand((2, 3))
x

tensor([[0.9330, 0.5613, 0.4517],
        [0.1306, 0.3180, 0.6821]])

In [25]:
torch.sum(x, dim=0)

tensor([1.0636, 0.8793, 1.1338])

In [26]:
torch.sum(x, dim=1)

tensor([1.9459, 1.1307])

In [27]:
torch.sum(x, dim=1).squeese(1)

AttributeError: 'Tensor' object has no attribute 'squeese'

In [28]:
torch.is_tensor(x)

True

In [29]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [33]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [35]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [36]:
y.shape

torch.Size([2, 2, 2])

In [38]:
y = torch.squeeze(x, 0)
x.shape, y.shape

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 1, 2, 1, 2]))

In [39]:
y = torch.squeeze(x, 1)
x.shape, y.shape

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 2, 1, 2]))

In [40]:
y = torch.squeeze(x, 2)
x.shape, y.shape

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 1, 2, 1, 2]))

In [41]:
y = torch.squeeze(x, 3)
x.shape, y.shape

(torch.Size([2, 1, 2, 1, 2]), torch.Size([2, 1, 2, 2]))

In [42]:
x = torch.zeros(5)
x

tensor([0., 0., 0., 0., 0.])

In [46]:
y = torch.unsqueeze(x, 0)
y, x.shape, y.shape

(tensor([[0., 0., 0., 0., 0.]]), torch.Size([5]), torch.Size([1, 5]))

In [49]:
torch.squeeze(y, 0)

tensor([0., 0., 0., 0., 0.])

In [45]:
torch.unsqueeze(x, 1)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [50]:
x = torch.arange(6).view(2,3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [51]:
torch.cat([x, x], dim=0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

In [52]:
torch.cat([x, x], dim=1)

tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])

In [54]:
torch.stack([x, x])

tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])

In [55]:
x = torch.ones(2, 2, requires_grad=True)

In [56]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [59]:
x.grad is None

True

In [60]:
y = (x + 2) * (x + 5) + 3

In [61]:
y

tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)

In [62]:
x.grad is None

True

In [63]:
z = y.mean()
z

tensor(21., grad_fn=<MeanBackward0>)

In [64]:
z.backward()

In [65]:
x.grad is None

False

In [66]:
x = torch.ones(5)
x

tensor([1., 1., 1., 1., 1.])

In [67]:
x.unsqueeze(0)

tensor([[1., 1., 1., 1., 1.]])

In [68]:
y = x.unsqueeze(0)
y

tensor([[1., 1., 1., 1., 1.]])

In [70]:
y.squeeze(0)

tensor([1., 1., 1., 1., 1.])

In [72]:
x = torch.rand(5, 7)
x

tensor([[0.2729, 0.0275, 0.4219, 0.7213, 0.3995, 0.4645, 0.0878],
        [0.7353, 0.9237, 0.3977, 0.0055, 0.3416, 0.8047, 0.0854],
        [0.6732, 0.4301, 0.0768, 0.6910, 0.4910, 0.5246, 0.3839],
        [0.0451, 0.1273, 0.7319, 0.1786, 0.7312, 0.6936, 0.7351],
        [0.0603, 0.5403, 0.4387, 0.9243, 0.7889, 0.5877, 0.9111]])

In [74]:
3 + x*4

tensor([[4.0917, 3.1099, 4.6875, 5.8852, 4.5982, 4.8581, 3.3513],
        [5.9412, 6.6947, 4.5906, 3.0221, 4.3665, 6.2188, 3.3416],
        [5.6927, 4.7204, 3.3074, 5.7642, 4.9642, 5.0986, 4.5357],
        [3.1803, 3.5093, 5.9274, 3.7143, 5.9247, 5.7742, 5.9404],
        [3.2411, 5.1611, 4.7548, 6.6974, 6.1557, 5.3508, 6.6444]])

In [75]:
x = torch.Tensor([1, 1, 1, 0, 1])
x

tensor([1., 1., 1., 0., 1.])

In [77]:
torch.nonzero(x)

tensor([[0],
        [1],
        [2],
        [4]])

In [78]:
x = torch.rand(3, 1)
x

tensor([[0.7247],
        [0.6254],
        [0.3723]])

In [80]:
torch.cat([x, x, x, x], dim=1)

tensor([[0.7247, 0.7247, 0.7247, 0.7247],
        [0.6254, 0.6254, 0.6254, 0.6254],
        [0.3723, 0.3723, 0.3723, 0.3723]])

In [82]:
torch.stack([x, x, x, x], dim=1)

tensor([[[0.7247],
         [0.7247],
         [0.7247],
         [0.7247]],

        [[0.6254],
         [0.6254],
         [0.6254],
         [0.6254]],

        [[0.3723],
         [0.3723],
         [0.3723],
         [0.3723]]])

In [83]:
x.expand(3, 4)

tensor([[0.7247, 0.7247, 0.7247, 0.7247],
        [0.6254, 0.6254, 0.6254, 0.6254],
        [0.3723, 0.3723, 0.3723, 0.3723]])

In [84]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)
a, b

(tensor([[[0.8393, 0.9766, 0.0661, 0.5189, 0.8730],
          [0.7964, 0.2380, 0.5482, 0.7357, 0.8449],
          [0.5789, 0.9559, 0.2056, 0.4542, 0.9229],
          [0.1443, 0.5014, 0.3532, 0.2894, 0.1067]],
 
         [[0.0107, 0.3797, 0.4900, 0.1494, 0.4190],
          [0.1301, 0.8278, 0.4500, 0.5657, 0.7408],
          [0.6867, 0.0243, 0.7522, 0.6611, 0.2138],
          [0.4941, 0.3830, 0.1627, 0.6559, 0.9827]],
 
         [[0.0199, 0.2489, 0.6842, 0.3024, 0.5272],
          [0.4149, 0.8469, 0.1357, 0.0336, 0.3021],
          [0.8910, 0.5096, 0.3006, 0.7743, 0.3053],
          [0.4332, 0.4966, 0.8116, 0.0231, 0.0039]]]),
 tensor([[[0.8070, 0.0850, 0.2525, 0.9439],
          [0.6798, 0.4328, 0.6046, 0.5290],
          [0.5719, 0.6703, 0.3459, 0.8070],
          [0.2667, 0.4997, 0.1940, 0.2463],
          [0.0641, 0.3166, 0.5528, 0.8954]],
 
         [[0.6565, 0.4616, 0.5882, 0.6938],
          [0.4124, 0.3878, 0.5425, 0.7278],
          [0.4744, 0.3619, 0.9012, 0.8753],
          [0

In [85]:
torch.bmm(a, b)

tensor([[[1.5733, 1.0740, 1.4084, 2.2717],
         [1.3683, 1.1732, 1.1443, 2.2576],
         [1.4148, 1.1199, 1.3935, 2.1562],
         [0.7433, 0.6444, 0.5769, 0.8533]],

        [[0.9094, 0.5790, 0.7683, 1.2175],
         [1.8028, 1.2697, 1.2177, 2.2619],
         [1.5743, 1.2784, 1.3169, 1.9585],
         [2.0218, 1.3091, 0.9988, 2.2345]],

        [[0.5058, 1.0716, 0.5346, 1.0497],
         [0.3970, 0.7281, 0.6717, 0.7984],
         [0.7841, 1.8324, 1.0796, 1.4715],
         [0.5266, 1.1911, 0.8623, 1.1608]]])

In [87]:
b = torch.rand(5, 4)
b

tensor([[0.4185, 0.5177, 0.3883, 0.6460],
        [0.4859, 0.2069, 0.7483, 0.9627],
        [0.3063, 0.9810, 0.5083, 0.9172],
        [0.5286, 0.3040, 0.8463, 0.4870],
        [0.9268, 0.4303, 0.1395, 0.0547]])

In [88]:
b.unsqueeze(0)

tensor([[[0.4185, 0.5177, 0.3883, 0.6460],
         [0.4859, 0.2069, 0.7483, 0.9627],
         [0.3063, 0.9810, 0.5083, 0.9172],
         [0.5286, 0.3040, 0.8463, 0.4870],
         [0.9268, 0.4303, 0.1395, 0.0547]]])

In [89]:
b.unsqueeze(0).shape

torch.Size([1, 5, 4])

In [90]:
b.unsqueeze(0).expand(a.size(0), *b.size())

tensor([[[0.4185, 0.5177, 0.3883, 0.6460],
         [0.4859, 0.2069, 0.7483, 0.9627],
         [0.3063, 0.9810, 0.5083, 0.9172],
         [0.5286, 0.3040, 0.8463, 0.4870],
         [0.9268, 0.4303, 0.1395, 0.0547]],

        [[0.4185, 0.5177, 0.3883, 0.6460],
         [0.4859, 0.2069, 0.7483, 0.9627],
         [0.3063, 0.9810, 0.5083, 0.9172],
         [0.5286, 0.3040, 0.8463, 0.4870],
         [0.9268, 0.4303, 0.1395, 0.0547]],

        [[0.4185, 0.5177, 0.3883, 0.6460],
         [0.4859, 0.2069, 0.7483, 0.9627],
         [0.3063, 0.9810, 0.5083, 0.9172],
         [0.5286, 0.3040, 0.8463, 0.4870],
         [0.9268, 0.4303, 0.1395, 0.0547]]])

In [93]:
b.size()

torch.Size([5, 4])

In [94]:
b.unsqueeze(0).expand(a.size(0), b.size()[0], b.size()[1])

tensor([[[0.4185, 0.5177, 0.3883, 0.6460],
         [0.4859, 0.2069, 0.7483, 0.9627],
         [0.3063, 0.9810, 0.5083, 0.9172],
         [0.5286, 0.3040, 0.8463, 0.4870],
         [0.9268, 0.4303, 0.1395, 0.0547]],

        [[0.4185, 0.5177, 0.3883, 0.6460],
         [0.4859, 0.2069, 0.7483, 0.9627],
         [0.3063, 0.9810, 0.5083, 0.9172],
         [0.5286, 0.3040, 0.8463, 0.4870],
         [0.9268, 0.4303, 0.1395, 0.0547]],

        [[0.4185, 0.5177, 0.3883, 0.6460],
         [0.4859, 0.2069, 0.7483, 0.9627],
         [0.3063, 0.9810, 0.5083, 0.9172],
         [0.5286, 0.3040, 0.8463, 0.4870],
         [0.9268, 0.4303, 0.1395, 0.0547]]])

In [95]:
b.unsqueeze(0).expand(a.size(0), *b.size()).shape

torch.Size([3, 5, 4])

In [98]:
a.size(0)

3

In [ ]:
class Perseptron(nn.Module):
    def __init__(self, input_dim):
        super(Perseptron, self).__init__()
        self.fc = nn.Linear(input_dim, 1)
        
    def forward(x_in):
        return torch.sigmoid(self.fc(x_in))

In [ ]:
# Каждая из эпох представляет собой полный проход
# по обучающей последовательности
for epoch_i in range(n_epochs):
    # Проходим во внутреннем цикле по пакетам набора данных
    for batch_i in range(n_batches):
        # Шаг 0: получаем данные
        x_data, y_target = get_toy_data(batch_size)
        # Шаг 1: очищаем значения градиентов
        perceptron.zero_grad()
        # Шаг 2: вычисляем прямой проход модели
        y_pred = perceptron(x_data, apply_sigmoid=True)
        # Шаг 3: вычисляем оптимизируемую величину потерь
        loss = bce_loss(y_pred, y_target)
        # Шаг 4: транслируем сигнал потерь обратно по графу вычислений
        loss.backward()
        # Шаг 5: запускаем выполнение обновления оптимизатором
        optimizer.step()